version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
  web:
    build: .
    ports:
      - "8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo

