version: '3'

services:
  nginx:
    build: ./nginx-dev
    ports:
      - '80:80'
      - '443:443'
  web:
    build: .
    ports:
      - "8080"
    networks:
      - default
    volumes:
      - .:/app
  db:
    image: mongo
